# The URL the site will be built for
base_url = "https://erg-lang.org"

title = "Erg Programming Language"

description = "Erg Programming Language"

compile_sass = true
generate_feed = true

theme = "juice"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "OneHalfDark"

[extra]
# Put all your custom variables here

juice_logo_name = ""
juice_logo_path = "logo.svg"
juice_extra_menu = [
    { title = "Github", link = "https://github.com/erg-lang"}
]

repository_url = "https://github.com/erg-lang/erg-lang.org"